const $=id=>document.getElementById(id);
const templates={
"VetPro VP50":{issues:["Error 2 warning","Error 3 warning","Pressure error","Battery not holding charge","Air bubble detection intermittent","Pump not moving fluid","Continuing to drip","High pressure / occlusion issue","Scheduled service"],actions:["Clean and inspect pump","Inspect system logs","Scheduled service","Replace battery","Replace driver board","Replace pressure sensor","Replace motor","Replace air bubble sensors","Update software","Update drug library","Calibrate pressure sensors","Calibrate occlusion pressure","Test pump"],tests:["Test with Gossen Metrawatt Seculife IF+ Infusion Analyzer","Use new Vetpump Pro VP50 IV Set","Rate test - 10ml at 35.00ml/h","Volume test - 10ml @ 35ml/h","Bolus test - OK","Occlusion / pressure test - passed"]},
"Vetflow Pro SP50":{issues:["Error 2 warning","Error 13 warning","Cracked / non-responsive screen","Bent fixture lever","Broken push/pull box","Pressure error","Blank screen","Unexpected bolus / purge report","Scheduled service"],actions:["Clean and inspect pump","Inspect system logs","Scheduled service","Replace battery","Replace motor detect board","Replace communication cable","Replace fixture lever","Replace pressure sensor","Replace driver board","Replace push/pull assembly","Replace screen / screen protector","Replace mainboard","Calibrate pump","Test pump"],tests:["Test with Gossen Metrawatt Seculife IF+ Infusion Analyzer","Use ZebraVet 10mm syringe","Rate test - passed","Volume test - passed","Bolus test - OK"]},
"V5 Infusion Pump":{issues:["Scheduled service","Battery issue","Flow / delivery issue","Alarm / error warning"],actions:["Clean and inspect pump","Scheduled service","Replace battery","Calibrate pump","Test pump"],tests:["Infusion analyzer test - passed","Rate test - passed","Volume test - passed","Bolus test - OK"]},
"Combispin":{issues:["Scheduled service","Operational fault","Noise / vibration"],actions:["Clean and inspect","Service unit","Test operation"],tests:["Operational test - passed"]},
"X23 Autoclave":{issues:["Scheduled service","Heating / cycle issue","Pressure issue"],actions:["Clean and inspect","Service autoclave","Inspect seals","Test cycle"],tests:["Cycle test - passed"]},
"Trinoc Microscope":{issues:["Scheduled service","Dust / contamination","Image quality issue"],actions:["Dismantle and clean internal optical surfaces","Reassemble microscope","Compare image quality with reference microscope","Test operation"],tests:["Visual / operational test - passed"]},
"Other / Custom":{issues:["Scheduled service","Not powering on","Physical damage","Intermittent fault"],actions:["Clean and inspect equipment","Diagnose reported fault","Repair / replace faulty component","Test equipment"],tests:["Operational test - passed"]}
};
const seedClinics=["SASH Adelaide","ARH Essendon Fields","The Austin Vet Specialists","Greencross Vets Fairymeadow","SASH","Greencross Woolloongabba","North Shore Vet Hospital","AEC Woolloongabba","Animal Referral Hospital Canberra","Killarney Vets","Companion Animal Vet Hospital","ARH Canberra","Greencross Vets Woolloongabba","Greencross Vets Macedon Ranges","Perth Vet Specialists","Rossmore Vet Hospital","AWL Gold Coast","ARH Brisbane","Vetland Hospital & Emergency","AWL - Brisbane Community Clinic","Greencross Noosa","Greencross Vets Midland","Greencross Vets Kilsyth","Animal Welfare League Ipswich","Greencross Vets Kenmore","Greencross Vets Teneriffe","Greencross Vets Forest Lake","Tuggerah Animal Hospital","Maryborough Veterinary Surgery","AWLQ Daisy Hill","Woombye Veterinary Surgery","Brisbane Veterinary Specialist Centre","Melbourne Animal Specialist Hospital","Greencross Vets Pimpama","Worongary Vets","Greencross Vets Kawana Waters","Animal Welfare League Brisbane","Vetlove Helensvale","Sydney Animal Hospital Norwest","Greencross Vets Cranbourne","Greencross Vets Craigieburn","Greencross Vets Point Cook","Greencross Vets Stud Park","Greencross Vets Moorooka","Greencross Vets Narellan","Greencross Vets Kedron","Greencross Vets Aitkenvale","Greencross Vets Deeragun","Greencross Vets Joondalup","Greencross Vets Box Hill","Greencross Vets South Morang","Greencross Vets Warringal","Greencross Vets White Hills","Greencross Vets Wyong","Vetlove Ballina","Vetlove Goonellabah","Vetlove Strathpine","Adelaide Plains Vet","Adelaide Veterinary Surgical Services","AEC Frankston","AEC Mount Waverley","AEC Varsity Lakes","Animal Referral Hospital Brisbane","Animal Referral Hospital Homebush","Balmain Veterinary Hospital","Burpengary Vets","Capalaba Vet","Cat Clinic Gold Coast","Coomera Springs Vet","Drouin Veterinary Clinic","Emergency Vet Adelaide","Erina Heights Veterinary Hospital","Ferntree Gully Veterinary Hospital","High Wycombe Vet Hospital","Indooroopilly Veterinary Clinic","Kangaroo Island Veterinary Clinic","Maclean Vet Hospital","Mandurah Emergency Vets","Manly Road Veterinary Hospital","Murray Bridge Vet Clinic","Narangba Veterinary Clinic","North Nowra Veterinary Hospital","Northern Beaches Vet Clinic","Park Ridge Animal Hospital","Peregian Springs Vet","River Rd Veterinary Clinic","Sippy Creek Animal Refuge","Swan Valley Vet Centre","Terrigal Vet Hospital","Toowoomba Veterinary Hospital","Victoria Point Veterinary Hospital","West Toowoomba Vets","Yamba Vet Clinic","Yandina Veterinary Clinic"];
let photos=[],deferredPrompt;
function allClinics(){return [...new Set([...seedClinics,...JSON.parse(localStorage.getItem("vet1Clinics")||"[]").map(x=>x.name)])].sort()}
function renderClinics(){ $("clinicList").innerHTML=allClinics().map(x=>'<option value="'+esc(x)+'"></option>').join("")}
function renderModels(){ $("model").innerHTML=Object.keys(templates).map(x=>'<option>'+x+'</option>').join("");renderTemplate()}
function chipHTML(x,kind){return '<button type="button" class="chip" data-kind="'+kind+'" data-text="'+esc(x)+'">'+esc(x)+'</button>'}
function renderTemplate(){let t=templates[$("model").value]||templates["Other / Custom"];$("issueChips").innerHTML=t.issues.map(x=>chipHTML(x,"issue")).join("");$("actionChips").innerHTML=t.actions.map(x=>chipHTML(x,"work")).join("");$("testChips").innerHTML=t.tests.map(x=>chipHTML(x,"tests")).join("");update()}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function append(id,text){let el=$(id),lines=el.value.split("\n").filter(Boolean);if(!lines.includes(text)) lines.push(text);el.value=lines.join("\n");update()}
document.addEventListener("click",e=>{let c=e.target.closest(".chip");if(c){c.classList.toggle("on");if(c.classList.contains("on"))append(c.dataset.kind,c.dataset.text)}})
function val(id){return $(id).value.trim()}
function update(){
 let p=photos.map(x=>'<img src="'+x+'">').join("");
 $("sheet").innerHTML='<div class="sheet-head"><div class="sheet-logo">V1</div><div><div class="sheet-title">Vet1 Equipment Service & Repair Form</div><div>1300 378 713 · service@vet1.com.au · Vet1.com.au</div></div></div>'+
 row("Machine / Model",val("model"))+row("Serial Number",val("serial"))+row("Included Accessories",val("accessories"))+
 '<div class="section">REPORTED ISSUE</div><div>'+nl(val("issue"))+'</div><div class="section">WORK COMPLETED / LOAN DETAILS</div><div>'+nl(val("work"))+'</div>'+
 (val("tests")?'<div class="section">TESTING</div><div>'+nl(val("tests"))+'</div>':'')+
 row("Clinic Name",val("clinic"))+row("Phone",val("phone"))+row("Email",val("email"))+row("Serviced by",val("tech"))+row("Date Completed",val("date"))+
 (val("due")?row("Next Service Due",val("due")):"")+(val("notes")?'<div class="section">NOTES</div><div>'+nl(val("notes"))+'</div>':'')+
 (p?'<div class="section">PHOTOS</div><div class="photos">'+p+'</div>':'');
}
function row(a,b){return '<div class="row"><b>'+esc(a)+'</b><span>'+esc(b||"")+'</span></div>'}
function nl(x){return esc(x).replace(/\n/g,"<br>")}
["clinic","phone","email","serial","accessories","issue","work","tests","tech","date","due","status","notes"].forEach(id=>$(id).addEventListener("input",update));
$("model").addEventListener("change",renderTemplate);
$("clinic").addEventListener("change",()=>{let saved=JSON.parse(localStorage.getItem("vet1Clinics")||"[]").find(x=>x.name.toLowerCase()===val("clinic").toLowerCase());if(saved){$("phone").value=saved.phone||"";$("email").value=saved.email||""}update()});
function rememberClinic(){let name=val("clinic");if(!name)return;let arr=JSON.parse(localStorage.getItem("vet1Clinics")||"[]"),i=arr.findIndex(x=>x.name.toLowerCase()===name.toLowerCase()),o={name,phone:val("phone"),email:val("email")};if(i>=0)arr[i]=o;else arr.push(o);localStorage.setItem("vet1Clinics",JSON.stringify(arr));renderClinics()}
$("photoInput").addEventListener("change",async e=>{photos=[];for(let f of [...e.target.files].slice(0,4)){photos.push(await compress(f))}update()});
function compress(file){return new Promise(res=>{let r=new FileReader;r.onload=()=>{let im=new Image;im.onload=()=>{let max=1200,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=im.width*s;c.height=im.height*s;c.getContext("2d").drawImage(im,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",.75))};im.src=r.result};r.readAsDataURL(file)})}
$("clearBtn").onclick=()=>{if(!confirm("Start a new report?"))return;document.querySelectorAll("input,textarea").forEach(x=>{if(x.type!=="file")x.value=""});photos=[];$("date").value=new Date().toISOString().slice(0,10);document.querySelectorAll(".chip").forEach(x=>x.classList.remove("on"));update()}
$("pdfBtn").onclick=async()=>{rememberClinic();$("msg").textContent="Creating PDF…";try{const {jsPDF}=window.jspdf;let pdf=new jsPDF({unit:"mm",format:"a4"}),y=15,teal=[16,167,178];pdf.setFillColor(...teal);pdf.circle(20,18,7,"F");pdf.setTextColor(255);pdf.setFont("helvetica","bold");pdf.setFontSize(10);pdf.text("V1",20,20,{align:"center"});pdf.setTextColor(23,50,58);pdf.setFontSize(16);pdf.text("Vet1 Equipment Service & Repair Form",32,17);pdf.setFont("helvetica","normal");pdf.setFontSize(8);pdf.text("1300 378 713  |  service@vet1.com.au  |  Vet1.com.au",32,22);pdf.setDrawColor(...teal);pdf.setLineWidth(1.4);pdf.line(14,28,196,28);y=35;
const add=(label,text)=>{if(!text)return;pdf.setFont("helvetica","bold");pdf.setFontSize(8);pdf.setTextColor(8,125,136);pdf.text(label.toUpperCase(),14,y);y+=4;pdf.setFont("helvetica","normal");pdf.setFontSize(9);pdf.setTextColor(23,50,58);let lines=pdf.splitTextToSize(text,180);pdf.text(lines,14,y);y+=lines.length*4.2+4;if(y>265){pdf.addPage();y=16}};
add("Machine / Model",val("model"));add("Serial Number",val("serial"));add("Included Accessories",val("accessories"));add("Reported issue",val("issue"));add("Work Completed / Loan Details",val("work"));add("Testing",val("tests"));add("Clinic",val("clinic"));add("Phone",val("phone"));add("Email",val("email"));add("Serviced by",val("tech"));add("Date Completed",val("date"));add("Next Service Due",val("due"));add("Status",val("status"));add("Notes",val("notes"));
for(let src of photos){if(y>210){pdf.addPage();y=16}try{pdf.addImage(src,"JPEG",14,y,80,60);y+=65}catch{}}
pdf.setFontSize(8);pdf.setTextColor(100);pdf.text("Vet1 Equipment Service & Repair",14,290);let name=(val("clinic")||"Clinic").replace(/[^a-z0-9]+/gi,"-")+"-"+(val("serial")||val("date")||"report")+".pdf";pdf.save(name);$("msg").textContent="PDF saved.";setTimeout(()=>$("msg").textContent="",2500)}catch(err){$("msg").textContent="PDF export needs an internet connection the first time this app is opened.";console.error(err)}};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").hidden=false});$("installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("installBtn").hidden=true}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
renderClinics();renderModels();$("date").value=new Date().toISOString().slice(0,10);update();